---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ghp.
--- DateTime: 2023/7/19 15:32
--- Description stream实现消息队列
---
-- 队列名
local queueName = ARGV[1]
-- 组名
local groupName = ARGV[2]

-- 检查流是否存在
local isExist = redis.call('EXISTS', queueName)

if isExist == 0 then
    -- 不存在则创建
    redis.call('XGROUP', 'CREATE', queueName, groupName, '$', 'MKSTREAM');
    return 1;
end

-- 存在
return 0;
